services:
  kronos:
    image: ghcr.io/ostafen/kronos
    ports:
      - '3010:9175'
    environment:
      - PORT=9175
      - STORE_PATH=/data/kronos
    volumes:
      - ./data:/data

volumes:
  kronos-data:
